"""Validate executed analyses and build a local reading index and output manifest."""
from pathlib import Path
import json,hashlib,sys,platform,re,html
import nbformat
import pandas as pd
from PIL import Image
R=Path(__file__).resolve().parents[2];O=R/'outputs';V=O/'validation'
logs=json.loads((V/'execution_log.json').read_text());sources=sorted((R/'notebooks/source').glob('*.ipynb'));errors=[]
for p in sources:
 n=p.stem;executed=R/'notebooks/executed'/p.name
 if not executed.exists():errors.append('Missing executed notebook '+n);continue
 nb=nbformat.read(executed,as_version=4);code=[c for c in nb.cells if c.cell_type=='code']
 if any(c.execution_count is None or any(o.output_type=='error' for o in c.outputs) for c in code):errors.append('Unexecuted or failed cell '+n)
 if logs.get(n,{}).get('source_sha256')!=hashlib.sha256(p.read_bytes()).hexdigest():errors.append('Source changed since execution '+n)
 if logs.get(n,{}).get('executed_sha256')!=hashlib.sha256(executed.read_bytes()).hexdigest():errors.append('Executed notebook changed '+n)
 if logs.get(n,{}).get('status')!='PASS':errors.append('Execution did not pass '+n)
 raw=executed.read_text()
 if any(x in raw for x in ['/Users/avssp','/private/tmp/fancode','Generated by ChatGPT','Author: OpenAI']):errors.append('Local path or authorship leak '+n)
 if not (O/'reports'/f'{n}.html').exists():errors.append('Missing HTML '+n)
for p in (O/'figures/png').glob('*.png'):
 with Image.open(p) as im:
  im.verify()
 if not (O/'figures/svg'/f'{p.stem}.svg').exists():errors.append('Missing editable vector '+p.stem)
for p in V.glob('*.json'):
 if p.name in ['execution_log.json','analysis_validation.json','output_manifest.json']:continue
 x=json.loads(p.read_text())
 if 'result' in x and x['result']!='PASS':errors.append('Failed check '+p.name)
# Independently verify crucial economic numbers with Decimal arithmetic.
from decimal import Decimal as D
expected=D(399)/D('1.18')-D(399)*D('.02')*D('1.18')-D(30)-D(175)
econ=pd.read_csv(O/'tables/07_contribution_grid.csv');r=econ[(econ.price==399)&(econ.tax==.18)&(econ.other_variable_cost==30)&(econ.cac==175)].iloc[0]
if abs(float(expected)-r.after_acquisition)>1e-8:errors.append('Independent contribution check')
# Test set-cover outcome against direct purchase alternatives for bounded tennis baskets.
b=pd.read_csv(O/'tables/03_minimum_cost_baskets.csv')
for row in b[b.basket=='Two tennis events within 30d'].itertuples():
 expected=min(2*row.tournament_price,399,row.monthly_price if row.monthly_atp else float('inf'),row.yearly_price)
 if row.total_cost!=expected:errors.append('Independent two-event coverage check')
gates=pd.read_csv(O/'tables/08_gate_allocation.csv')
if abs(gates.total.sum()-30400000)>1e-6 or abs(gates.gate1.sum()-100000)>1e-6 or abs(gates.gate2.sum()-7500000)>1e-6 or abs(gates.gate3.sum()-22800000)>1e-6:errors.append('Envelope or gates do not reconcile')
# Aggregate traces are lineage summaries, not every field's source. Row tables retain detailed locators.
trace={}
for line in (V/'artifact_trace.jsonl').read_text().splitlines():
 x=json.loads(line);trace[x['artifact']]=x
for relative,x in trace.items():
 if not (R/relative).exists() or hashlib.sha256((R/relative).read_bytes()).hexdigest()!=x['sha256']:errors.append('Trace checksum mismatch '+relative)
(V/'artifact_lineage.json').write_text(json.dumps(list(trace.values()),indent=2)+'\n')
summary={'result':'FAIL' if errors else 'PASS','author':'Chanakya','raw_release':'raw-v5-2026-09-14','executed_notebooks':len(sources),'executed_code_cells':sum(x.get('executed_cells',0) for x in logs.values()),'output_tables':len(list((O/'tables').glob('*.csv'))),'processed_tables':len(list((R/'data/processed').glob('*.csv'))),'png_figures':len(list((O/'figures/png').glob('*.png'))),'svg_figures':len(list((O/'figures/svg').glob('*.svg'))),'html_notebooks':len(list((O/'reports').glob('[0-9][0-9]_*.html'))),'errors':errors,'notes':['Fresh kernels, regenerated processed/output folders, offline raw inputs.','Source and executed notebook checksums match.','Independent Decimal contribution and two-event coverage checks passed if result is PASS.','Native kernel shutdown reported a macOS process-enumeration permission warning. It did not interrupt completed cells or exports.','Results are public-data analyses and explicit scenarios, not measured internal cohorts or causal tests.']}
(V/'analysis_validation.json').write_text(json.dumps(summary,indent=2)+'\n')
if errors:print(json.dumps(summary,indent=2));raise SystemExit(1)
modules={
'00':'Raw integrity, brief definitions and requirement coverage',
'01':'Primary ATP calendar, 12-final comparison and timing sensitivity',
'02':'F1/football clashes, MotoGP clock quarantine and co-occurrence',
'03':'Product audit, exact coverage baskets and dynamic-pricing rules',
'04':'Review friction, store/period controls and exploratory text themes',
'05':'Search interest, rounding, correlation and temporal diagnostics',
'06':'Historical player progression, bundle risk and video metadata',
'07':'Contribution, tax, repeat, credit, usage costs and rights horizon',
'08':'The economics model: two cohorts, channel CAC, break-even upgrade rate and gate sizing',
'09':'Retention journeys, KPI denominators, experiments and power',
'10':'Campaign-ready windows: the 2026 ATP calendar scored for India'}
rows=[]
for p in sources:
 n=p.stem;prefix=n[:2];count=sum(x['notebook']==n and x['kind']=='figure' and x['artifact'].endswith('.png') for x in trace.values())
 rows.append(f'<tr><td><a href="{n}.html">{html.escape(n.replace("_"," "))}</a></td><td>{modules[prefix]}</td><td>{logs[n]["executed_cells"]}</td><td>{count}</td><td><a href="../../notebooks/executed/{p.name}">Executed notebook</a></td></tr>')
body=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FanCode ATP analysis | Chanakya</title>
<style>body{{font:15px/1.55 system-ui,sans-serif;color:#193047;background:#f3f7fc;margin:0}}main{{max-width:1200px;margin:auto;padding:36px}}h1{{font-size:34px;margin:0}}h2{{margin-top:32px}}.eyebrow{{color:#087b80;font-weight:700}}.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:24px 0}}.card{{background:white;border-top:4px solid #00a398;padding:16px}}.big{{display:block;font-size:28px;font-weight:750}}table{{border-collapse:collapse;width:100%;background:white}}td,th{{text-align:left;border-bottom:1px solid #dce5ef;padding:12px;vertical-align:top}}th{{background:#e1edf9}}a{{color:#125ca8}}.note{{padding:18px;background:#fff3dc;border-left:4px solid #eea127}}img{{max-width:100%;background:white}}small{{color:#526170}}@media(max-width:750px){{.cards{{grid-template-columns:repeat(2,1fr)}}main{{padding:18px}}table{{font-size:12px}}}}</style>
<main><div class="eyebrow">COMPETITION TEAM · OFFLINE RESEARCH PACKAGE</div><h1>FanCode ATP: from viewing occasions to profitable relationships</h1><p>Executed analyses using locked raw-v5 inputs. Read in numerical order. Notebook 08 holds every economic figure; notebook 10 is the campaign-ready windows list. HTML versions include the code, tables and charts.</p>
<div class="cards"><div class="card"><span class="big">{len(sources)}</span>executed notebooks</div><div class="card"><span class="big">{summary['output_tables']}</span>output tables</div><div class="card"><span class="big">{summary['png_figures']}</span>charts, PNG + SVG</div><div class="card"><span class="big">PASS</span>execution and package checks</div></div>
<div class="note"><b>Evidence boundaries.</b> No survey respondents, internal company cohorts or causal experiment results are invented. Current monthly ATP inclusion remains a branch in the model. Unit costs, observed prices, case assumptions and response scenarios are labelled separately. Row-level review text remains local-only.</div>
<h2>Notebook library</h2><table><thead><tr><th>Read HTML</th><th>Analytical purpose</th><th>Code cells</th><th>Charts</th><th>Download</th></tr></thead><tbody>{''.join(rows)}</tbody></table>
<h2>Decision evidence</h2><p><a href="08_economics_findings.md">Economics findings</a> · <a href="../tables/08_break_even_rates.csv">Break-even upgrade rates</a> · <a href="../tables/08_gate_allocation.csv">Allocation by gate</a> · <a href="10_campaign_windows_findings.md">Campaign windows findings</a> · <a href="../tables/10_campaign_ready_windows.csv">Campaign-ready windows list</a> · <a href="../validation/analysis_validation.json">Validation report</a> · <a href="../../README.md">Reproduction guide</a></p>
<h2>Representative outputs</h2><img src="../figures/png/01_final_start_times.png" alt="Selected final starts in India time"><img src="../figures/png/03_basket_switch_map.png" alt="Minimum cost under alternative entitlement assumptions"><img src="../figures/png/08_break_even_curve.png" alt="Net at 24 months against the treatment upgrade rate"><img src="../figures/png/10_campaign_windows_calendar.png" alt="2026 ATP windows by India start time"><p><small>Collection snapshots: 13–14 September 2026. Review cutoff: 12 September 2026. Analysis: 15 September 2026. Presentation construction and publication are separate steps.</small></p></main></html>'''
(O/'reports/index.html').write_text(body)
runtime={'python':platform.python_version(),'platform_family':sys.platform,'kernel':'Python ipykernel, independent kernel per notebook','dependencies':'requirements-analysis.lock.txt','seed':20260915,'execution_order':[p.stem for p in sources]}
(V/'analysis_runtime.json').write_text(json.dumps(runtime,indent=2)+'\n')
files=[]
for folder in [R/'notebooks/source',R/'notebooks/executed',R/'data/processed',O/'tables',O/'figures',O/'reports']:
 for p in sorted(folder.rglob('*')):
  if p.is_file():files.append({'file':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'redistribution':'Local-only review text' if 'local_only' in p.name else 'Review source rights before publication'})
(V/'output_manifest.json').write_text(json.dumps(files,indent=2)+'\n')
print(json.dumps(summary,indent=2))
